### PR TITLE
Upgrade to Elm 0.19

### PR DESCRIPTION
**Pull request by jackfranklin**
Hello,

Thanks for the work on this! This PR upgrades the package to 0.19. I'd be grateful if you could merge + publish this as we rely on it in production and we'd love to get onto 0.19 soon :)

I ditched the `examples/Window.elm` as `elm make` doesn't allow an effect manager.

### CODE REVIEW

**Comment by rgrempel** [comment]
Thanks for this, and for your work on the proper-keyboard dependency!

I'll review this ASAP.

**Comment by rgrempel** [comment]
I've read through this quickly -- looks good -- thanks again.

I'll go ahead and merge this and then make a few more tweaks.

**Comment by rgrempel** [comment]
I've published version 1.0.1 for Elm 0.19.

Thanks again for your work on this. I took the opportunity to re-write the documentation, to take into account various changes between Elm 0.18 and 0.19.

For listening to global keypresses, it turns out that Elm 0.19 is actually improved, because the listeners in `Browser.Events` let you provide your own decoder. (Previously, they only gave you access to the KeyCode). So, I was able to restore the "listen to global events" example -- you don't need to write your own effects manager to do that in Elm 0.19, which is nice.

**Comment by jackfranklin** [comment]
@rgrempel thanks for acting so promptly on this! That's great news about global keypresses, sorry I didn't realise that yesterday. Thanks so much for merging + your work on this module :)

**Pull request merged**
